const CLIENT_NAME_MAX = 100;
const CLIENT_CODE_MAX = 50;
const CLIENT_ADDRESS_MAX = 255;

const PROJECT_NAME_MAX = 100;
const PROJECT_CODE_MAX = 50;
const NOTE_MAX = 1000;

export {
  CLIENT_NAME_MAX,
  CLIENT_CODE_MAX,
  CLIENT_ADDRESS_MAX,
  PROJECT_NAME_MAX,
  PROJECT_CODE_MAX,
  NOTE_MAX,
};
